### PR TITLE
added support for sect5 as well as sect4 via passthroughs

### PR DESCRIPTION
**Pull request by sarahs**

### CODE REVIEW

**Comment by wanwis230961** [comment]
https://github.com/oreillymedia/docbook2asciidoc/pull/22#issue-7328814

**Comment by samuelmonday6** [comment]
Plea Highlight
Respond
Share
00. Du.
Tom is a crypto enthusiast. He is a Curve investor and currently holding Curve stable swap pool LP tokens. As more DeFi projects emerge, he is willing to invest.

**Comment by Ibyuseef4** [comment]
Yolo

**Comment by sakariyefaysal06-hash** [comment]
Sakariye Faysal

**Pull request merged**
